--
-- PostgreSQL database dump
--

-- Dumped from database version 15.1 (Ubuntu 15.1-1.pgdg20.04+1)
-- Dumped by pg_dump version 16.1

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

--
-- Name: public; Type: SCHEMA; Schema: -; Owner: pg_database_owner
--

CREATE SCHEMA public;


ALTER SCHEMA public OWNER TO pg_database_owner;


--
-- Name: SCHEMA public; Type: COMMENT; Schema: -; Owner: pg_database_owner
--

COMMENT ON SCHEMA public IS 'standard public schema';


SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- Name: arte_description; Type: TABLE; Schema: public; Owner: supabase_admin
--

CREATE TABLE public.arte_description (
    id bigint NOT NULL,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    id_thing bigint NOT NULL,
    id_lang smallint NOT NULL,
    subtitle text,
    description text,
    full_description text
);


ALTER TABLE public.arte_description OWNER TO supabase_admin;

--
-- Name: cover; Type: TABLE; Schema: public; Owner: supabase_admin
--

CREATE TABLE public.cover (
    id bigint NOT NULL,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    id_thing bigint NOT NULL,
    id_lang smallint NOT NULL,
    file text NOT NULL
);


ALTER TABLE public.cover OWNER TO supabase_admin;

--
-- Name: COLUMN cover.file; Type: COMMENT; Schema: public; Owner: supabase_admin
--

COMMENT ON COLUMN public.cover.file IS 'base64';


--
-- Name: arte_image_id_seq; Type: SEQUENCE; Schema: public; Owner: supabase_admin
--

ALTER TABLE public.cover ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.arte_image_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: arte_info; Type: TABLE; Schema: public; Owner: supabase_admin
--

CREATE TABLE public.arte_info (
    id bigint NOT NULL,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    id_thing bigint NOT NULL,
    duration smallint,
    years smallint[],
    actors text[],
    authors text[],
    directors text[],
    countries text[],
    productors text[]
);


ALTER TABLE public.arte_info OWNER TO supabase_admin;

--
-- Name: arte_info_id_seq; Type: SEQUENCE; Schema: public; Owner: supabase_admin
--

ALTER TABLE public.arte_info ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.arte_info_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: language; Type: TABLE; Schema: public; Owner: supabase_admin
--

CREATE TABLE public.language (
    id smallint NOT NULL,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    tag text NOT NULL
);


ALTER TABLE public.language OWNER TO supabase_admin;

--
-- Name: language_id_seq; Type: SEQUENCE; Schema: public; Owner: supabase_admin
--

ALTER TABLE public.language ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.language_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: metadata_id_seq; Type: SEQUENCE; Schema: public; Owner: supabase_admin
--

ALTER TABLE public.arte_description ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.metadata_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: provider; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.provider (
    id smallint NOT NULL,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    label text NOT NULL,
    comment text
);


ALTER TABLE public.provider OWNER TO postgres;

--
-- Name: provider_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.provider ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.provider_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: subtitles; Type: TABLE; Schema: public; Owner: supabase_admin
--

CREATE TABLE public.subtitles (
    id bigint NOT NULL,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    id_thing bigint NOT NULL,
    id_provider smallint NOT NULL,
    id_lang smallint NOT NULL,
    ext text NOT NULL,
    file text NOT NULL
);


ALTER TABLE public.subtitles OWNER TO supabase_admin;

--
-- Name: subtitles_id_seq; Type: SEQUENCE; Schema: public; Owner: supabase_admin
--

ALTER TABLE public.subtitles ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.subtitles_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: thing; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.thing (
    id bigint NOT NULL,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    id_type smallint,
    arte text,
    imdb integer,
    tmdb integer
);


ALTER TABLE public.thing OWNER TO postgres;

--
-- Name: thing_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.thing ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.thing_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: title; Type: TABLE; Schema: public; Owner: supabase_admin
--

CREATE TABLE public.title (
    id bigint NOT NULL,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    id_thing bigint NOT NULL,
    id_lang smallint NOT NULL,
    is_original boolean,
    label text NOT NULL
);


ALTER TABLE public.title OWNER TO supabase_admin;

--
-- Name: title_id_seq; Type: SEQUENCE; Schema: public; Owner: supabase_admin
--

ALTER TABLE public.title ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.title_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: type; Type: TABLE; Schema: public; Owner: supabase_admin
--

CREATE TABLE public.type (
    id smallint NOT NULL,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    label text NOT NULL
);


ALTER TABLE public.type OWNER TO supabase_admin;

--
-- Name: type_id_seq; Type: SEQUENCE; Schema: public; Owner: supabase_admin
--

ALTER TABLE public.type ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.type_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: cover arte_image_pkey; Type: CONSTRAINT; Schema: public; Owner: supabase_admin
--

ALTER TABLE ONLY public.cover
    ADD CONSTRAINT arte_image_pkey PRIMARY KEY (id);


--
-- Name: arte_info arte_info_id_thing; Type: CONSTRAINT; Schema: public; Owner: supabase_admin
--

ALTER TABLE ONLY public.arte_info
    ADD CONSTRAINT arte_info_id_thing UNIQUE (id_thing);


--
-- Name: arte_info arte_info_pkey; Type: CONSTRAINT; Schema: public; Owner: supabase_admin
--

ALTER TABLE ONLY public.arte_info
    ADD CONSTRAINT arte_info_pkey PRIMARY KEY (id);


--
-- Name: language language_pkey; Type: CONSTRAINT; Schema: public; Owner: supabase_admin
--

ALTER TABLE ONLY public.language
    ADD CONSTRAINT language_pkey PRIMARY KEY (id);


--
-- Name: arte_description metadata_pkey; Type: CONSTRAINT; Schema: public; Owner: supabase_admin
--

ALTER TABLE ONLY public.arte_description
    ADD CONSTRAINT metadata_pkey PRIMARY KEY (id);


--
-- Name: provider provider_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.provider
    ADD CONSTRAINT provider_pkey PRIMARY KEY (id);


--
-- Name: subtitles subtitles_pkey; Type: CONSTRAINT; Schema: public; Owner: supabase_admin
--

ALTER TABLE ONLY public.subtitles
    ADD CONSTRAINT subtitles_pkey PRIMARY KEY (id);


--
-- Name: thing thing_id_arte_key; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.thing
    ADD CONSTRAINT thing_id_arte_key UNIQUE (arte);


--
-- Name: thing thing_id_imdb_key; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.thing
    ADD CONSTRAINT thing_id_imdb_key UNIQUE (imdb);


--
-- Name: thing thing_id_tmdb_key; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.thing
    ADD CONSTRAINT thing_id_tmdb_key UNIQUE (tmdb);


--
-- Name: thing thing_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.thing
    ADD CONSTRAINT thing_pkey PRIMARY KEY (id);


--
-- Name: title title_pkey; Type: CONSTRAINT; Schema: public; Owner: supabase_admin
--

ALTER TABLE ONLY public.title
    ADD CONSTRAINT title_pkey PRIMARY KEY (id);


--
-- Name: type type_pkey; Type: CONSTRAINT; Schema: public; Owner: supabase_admin
--

ALTER TABLE ONLY public.type
    ADD CONSTRAINT type_pkey PRIMARY KEY (id);


--
-- Name: cover uniq_cover_by_thing_n_lang; Type: CONSTRAINT; Schema: public; Owner: supabase_admin
--

ALTER TABLE ONLY public.cover
    ADD CONSTRAINT uniq_cover_by_thing_n_lang UNIQUE (id_thing, id_lang);


--
-- Name: arte_description uniq_description_by_thing_n_lang; Type: CONSTRAINT; Schema: public; Owner: supabase_admin
--

ALTER TABLE ONLY public.arte_description
    ADD CONSTRAINT uniq_description_by_thing_n_lang UNIQUE (id_thing, id_lang);


--
-- Name: language uniq_language_by_tag; Type: CONSTRAINT; Schema: public; Owner: supabase_admin
--

ALTER TABLE ONLY public.language
    ADD CONSTRAINT uniq_language_by_tag UNIQUE (tag);


--
-- Name: provider uniq_provider_by_label; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.provider
    ADD CONSTRAINT uniq_provider_by_label UNIQUE (label);


--
-- Name: subtitles uniq_subtitles_by_thing_n_lang_n_provider; Type: CONSTRAINT; Schema: public; Owner: supabase_admin
--

ALTER TABLE ONLY public.subtitles
    ADD CONSTRAINT uniq_subtitles_by_thing_n_lang_n_provider UNIQUE (id_thing, id_lang, id_provider);


--
-- Name: title uniq_title_by_thing_n_label; Type: CONSTRAINT; Schema: public; Owner: supabase_admin
--

ALTER TABLE ONLY public.title
    ADD CONSTRAINT uniq_title_by_thing_n_label UNIQUE (id_thing, label);


--
-- Name: type uniq_type_by_label; Type: CONSTRAINT; Schema: public; Owner: supabase_admin
--

ALTER TABLE ONLY public.type
    ADD CONSTRAINT uniq_type_by_label UNIQUE (label);


--
-- Name: arte_description arte_description_id_lang_fkey; Type: FK CONSTRAINT; Schema: public; Owner: supabase_admin
--

ALTER TABLE ONLY public.arte_description
    ADD CONSTRAINT arte_description_id_lang_fkey FOREIGN KEY (id_lang) REFERENCES public.language(id);


--
-- Name: arte_description arte_description_id_thing_fkey; Type: FK CONSTRAINT; Schema: public; Owner: supabase_admin
--

ALTER TABLE ONLY public.arte_description
    ADD CONSTRAINT arte_description_id_thing_fkey FOREIGN KEY (id_thing) REFERENCES public.thing(id);


--
-- Name: arte_info arte_info_id_thing_fkey; Type: FK CONSTRAINT; Schema: public; Owner: supabase_admin
--

ALTER TABLE ONLY public.arte_info
    ADD CONSTRAINT arte_info_id_thing_fkey FOREIGN KEY (id_thing) REFERENCES public.thing(id);


--
-- Name: cover cover_id_lang_fkey; Type: FK CONSTRAINT; Schema: public; Owner: supabase_admin
--

ALTER TABLE ONLY public.cover
    ADD CONSTRAINT cover_id_lang_fkey FOREIGN KEY (id_lang) REFERENCES public.language(id);


--
-- Name: cover cover_id_thing_fkey; Type: FK CONSTRAINT; Schema: public; Owner: supabase_admin
--

ALTER TABLE ONLY public.cover
    ADD CONSTRAINT cover_id_thing_fkey FOREIGN KEY (id_thing) REFERENCES public.thing(id);


--
-- Name: subtitles subtitles_id_lang_fkey; Type: FK CONSTRAINT; Schema: public; Owner: supabase_admin
--

ALTER TABLE ONLY public.subtitles
    ADD CONSTRAINT subtitles_id_lang_fkey FOREIGN KEY (id_lang) REFERENCES public.language(id);


--
-- Name: subtitles subtitles_id_provider_fkey; Type: FK CONSTRAINT; Schema: public; Owner: supabase_admin
--

ALTER TABLE ONLY public.subtitles
    ADD CONSTRAINT subtitles_id_provider_fkey FOREIGN KEY (id_provider) REFERENCES public.provider(id);


--
-- Name: subtitles subtitles_id_thing_fkey; Type: FK CONSTRAINT; Schema: public; Owner: supabase_admin
--

ALTER TABLE ONLY public.subtitles
    ADD CONSTRAINT subtitles_id_thing_fkey FOREIGN KEY (id_thing) REFERENCES public.thing(id);


--
-- Name: thing thing_id_type_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.thing
    ADD CONSTRAINT thing_id_type_fkey FOREIGN KEY (id_type) REFERENCES public.type(id);


--
-- Name: title title_id_lang_fkey; Type: FK CONSTRAINT; Schema: public; Owner: supabase_admin
--

ALTER TABLE ONLY public.title
    ADD CONSTRAINT title_id_lang_fkey FOREIGN KEY (id_lang) REFERENCES public.language(id);


--
-- Name: title title_id_thing_fkey; Type: FK CONSTRAINT; Schema: public; Owner: supabase_admin
--

ALTER TABLE ONLY public.title
    ADD CONSTRAINT title_id_thing_fkey FOREIGN KEY (id_thing) REFERENCES public.thing(id);


--
-- Name: arte_description; Type: ROW SECURITY; Schema: public; Owner: supabase_admin
--

ALTER TABLE public.arte_description ENABLE ROW LEVEL SECURITY;

--
-- Name: arte_info; Type: ROW SECURITY; Schema: public; Owner: supabase_admin
--

ALTER TABLE public.arte_info ENABLE ROW LEVEL SECURITY;

--
-- Name: cover; Type: ROW SECURITY; Schema: public; Owner: supabase_admin
--

ALTER TABLE public.cover ENABLE ROW LEVEL SECURITY;

--
-- Name: language; Type: ROW SECURITY; Schema: public; Owner: supabase_admin
--

ALTER TABLE public.language ENABLE ROW LEVEL SECURITY;

--
-- Name: provider; Type: ROW SECURITY; Schema: public; Owner: postgres
--

ALTER TABLE public.provider ENABLE ROW LEVEL SECURITY;

--
-- Name: subtitles; Type: ROW SECURITY; Schema: public; Owner: supabase_admin
--

ALTER TABLE public.subtitles ENABLE ROW LEVEL SECURITY;

--
-- Name: thing; Type: ROW SECURITY; Schema: public; Owner: postgres
--

ALTER TABLE public.thing ENABLE ROW LEVEL SECURITY;

--
-- Name: title; Type: ROW SECURITY; Schema: public; Owner: supabase_admin
--

ALTER TABLE public.title ENABLE ROW LEVEL SECURITY;

--
-- Name: type; Type: ROW SECURITY; Schema: public; Owner: supabase_admin
--

ALTER TABLE public.type ENABLE ROW LEVEL SECURITY;

--
-- Name: SCHEMA public; Type: ACL; Schema: -; Owner: pg_database_owner
--

GRANT USAGE ON SCHEMA public TO postgres;
GRANT USAGE ON SCHEMA public TO anon;
GRANT USAGE ON SCHEMA public TO authenticated;
GRANT USAGE ON SCHEMA public TO service_role;


--
-- Name: TABLE arte_description; Type: ACL; Schema: public; Owner: supabase_admin
--

GRANT ALL ON TABLE public.arte_description TO postgres;
GRANT ALL ON TABLE public.arte_description TO anon;
GRANT ALL ON TABLE public.arte_description TO authenticated;
GRANT ALL ON TABLE public.arte_description TO service_role;


--
-- Name: TABLE cover; Type: ACL; Schema: public; Owner: supabase_admin
--

GRANT ALL ON TABLE public.cover TO postgres;
GRANT ALL ON TABLE public.cover TO anon;
GRANT ALL ON TABLE public.cover TO authenticated;
GRANT ALL ON TABLE public.cover TO service_role;


--
-- Name: SEQUENCE arte_image_id_seq; Type: ACL; Schema: public; Owner: supabase_admin
--

GRANT ALL ON SEQUENCE public.arte_image_id_seq TO postgres;
GRANT ALL ON SEQUENCE public.arte_image_id_seq TO anon;
GRANT ALL ON SEQUENCE public.arte_image_id_seq TO authenticated;
GRANT ALL ON SEQUENCE public.arte_image_id_seq TO service_role;


--
-- Name: TABLE arte_info; Type: ACL; Schema: public; Owner: supabase_admin
--

GRANT ALL ON TABLE public.arte_info TO postgres;
GRANT ALL ON TABLE public.arte_info TO anon;
GRANT ALL ON TABLE public.arte_info TO authenticated;
GRANT ALL ON TABLE public.arte_info TO service_role;


--
-- Name: SEQUENCE arte_info_id_seq; Type: ACL; Schema: public; Owner: supabase_admin
--

GRANT ALL ON SEQUENCE public.arte_info_id_seq TO postgres;
GRANT ALL ON SEQUENCE public.arte_info_id_seq TO anon;
GRANT ALL ON SEQUENCE public.arte_info_id_seq TO authenticated;
GRANT ALL ON SEQUENCE public.arte_info_id_seq TO service_role;


--
-- Name: TABLE language; Type: ACL; Schema: public; Owner: supabase_admin
--

GRANT ALL ON TABLE public.language TO postgres;
GRANT ALL ON TABLE public.language TO anon;
GRANT ALL ON TABLE public.language TO authenticated;
GRANT ALL ON TABLE public.language TO service_role;


--
-- Name: SEQUENCE language_id_seq; Type: ACL; Schema: public; Owner: supabase_admin
--

GRANT ALL ON SEQUENCE public.language_id_seq TO postgres;
GRANT ALL ON SEQUENCE public.language_id_seq TO anon;
GRANT ALL ON SEQUENCE public.language_id_seq TO authenticated;
GRANT ALL ON SEQUENCE public.language_id_seq TO service_role;


--
-- Name: SEQUENCE metadata_id_seq; Type: ACL; Schema: public; Owner: supabase_admin
--

GRANT ALL ON SEQUENCE public.metadata_id_seq TO postgres;
GRANT ALL ON SEQUENCE public.metadata_id_seq TO anon;
GRANT ALL ON SEQUENCE public.metadata_id_seq TO authenticated;
GRANT ALL ON SEQUENCE public.metadata_id_seq TO service_role;


--
-- Name: TABLE provider; Type: ACL; Schema: public; Owner: postgres
--

GRANT ALL ON TABLE public.provider TO anon;
GRANT ALL ON TABLE public.provider TO authenticated;
GRANT ALL ON TABLE public.provider TO service_role;


--
-- Name: SEQUENCE provider_id_seq; Type: ACL; Schema: public; Owner: postgres
--

GRANT ALL ON SEQUENCE public.provider_id_seq TO anon;
GRANT ALL ON SEQUENCE public.provider_id_seq TO authenticated;
GRANT ALL ON SEQUENCE public.provider_id_seq TO service_role;


--
-- Name: TABLE subtitles; Type: ACL; Schema: public; Owner: supabase_admin
--

GRANT ALL ON TABLE public.subtitles TO postgres;
GRANT ALL ON TABLE public.subtitles TO anon;
GRANT ALL ON TABLE public.subtitles TO authenticated;
GRANT ALL ON TABLE public.subtitles TO service_role;


--
-- Name: SEQUENCE subtitles_id_seq; Type: ACL; Schema: public; Owner: supabase_admin
--

GRANT ALL ON SEQUENCE public.subtitles_id_seq TO postgres;
GRANT ALL ON SEQUENCE public.subtitles_id_seq TO anon;
GRANT ALL ON SEQUENCE public.subtitles_id_seq TO authenticated;
GRANT ALL ON SEQUENCE public.subtitles_id_seq TO service_role;


--
-- Name: TABLE thing; Type: ACL; Schema: public; Owner: postgres
--

GRANT ALL ON TABLE public.thing TO anon;
GRANT ALL ON TABLE public.thing TO authenticated;
GRANT ALL ON TABLE public.thing TO service_role;


--
-- Name: SEQUENCE thing_id_seq; Type: ACL; Schema: public; Owner: postgres
--

GRANT ALL ON SEQUENCE public.thing_id_seq TO anon;
GRANT ALL ON SEQUENCE public.thing_id_seq TO authenticated;
GRANT ALL ON SEQUENCE public.thing_id_seq TO service_role;


--
-- Name: TABLE title; Type: ACL; Schema: public; Owner: supabase_admin
--

GRANT ALL ON TABLE public.title TO postgres;
GRANT ALL ON TABLE public.title TO anon;
GRANT ALL ON TABLE public.title TO authenticated;
GRANT ALL ON TABLE public.title TO service_role;


--
-- Name: SEQUENCE title_id_seq; Type: ACL; Schema: public; Owner: supabase_admin
--

GRANT ALL ON SEQUENCE public.title_id_seq TO postgres;
GRANT ALL ON SEQUENCE public.title_id_seq TO anon;
GRANT ALL ON SEQUENCE public.title_id_seq TO authenticated;
GRANT ALL ON SEQUENCE public.title_id_seq TO service_role;


--
-- Name: TABLE type; Type: ACL; Schema: public; Owner: supabase_admin
--

GRANT ALL ON TABLE public.type TO postgres;
GRANT ALL ON TABLE public.type TO anon;
GRANT ALL ON TABLE public.type TO authenticated;
GRANT ALL ON TABLE public.type TO service_role;


--
-- Name: SEQUENCE type_id_seq; Type: ACL; Schema: public; Owner: supabase_admin
--

GRANT ALL ON SEQUENCE public.type_id_seq TO postgres;
GRANT ALL ON SEQUENCE public.type_id_seq TO anon;
GRANT ALL ON SEQUENCE public.type_id_seq TO authenticated;
GRANT ALL ON SEQUENCE public.type_id_seq TO service_role;


--
-- Name: DEFAULT PRIVILEGES FOR SEQUENCES; Type: DEFAULT ACL; Schema: public; Owner: postgres
--

ALTER DEFAULT PRIVILEGES FOR ROLE postgres IN SCHEMA public GRANT ALL ON SEQUENCES TO postgres;
ALTER DEFAULT PRIVILEGES FOR ROLE postgres IN SCHEMA public GRANT ALL ON SEQUENCES TO anon;
ALTER DEFAULT PRIVILEGES FOR ROLE postgres IN SCHEMA public GRANT ALL ON SEQUENCES TO authenticated;
ALTER DEFAULT PRIVILEGES FOR ROLE postgres IN SCHEMA public GRANT ALL ON SEQUENCES TO service_role;


--
-- Name: DEFAULT PRIVILEGES FOR SEQUENCES; Type: DEFAULT ACL; Schema: public; Owner: supabase_admin
--

ALTER DEFAULT PRIVILEGES FOR ROLE supabase_admin IN SCHEMA public GRANT ALL ON SEQUENCES TO postgres;
ALTER DEFAULT PRIVILEGES FOR ROLE supabase_admin IN SCHEMA public GRANT ALL ON SEQUENCES TO anon;
ALTER DEFAULT PRIVILEGES FOR ROLE supabase_admin IN SCHEMA public GRANT ALL ON SEQUENCES TO authenticated;
ALTER DEFAULT PRIVILEGES FOR ROLE supabase_admin IN SCHEMA public GRANT ALL ON SEQUENCES TO service_role;


--
-- Name: DEFAULT PRIVILEGES FOR FUNCTIONS; Type: DEFAULT ACL; Schema: public; Owner: postgres
--

ALTER DEFAULT PRIVILEGES FOR ROLE postgres IN SCHEMA public GRANT ALL ON FUNCTIONS TO postgres;
ALTER DEFAULT PRIVILEGES FOR ROLE postgres IN SCHEMA public GRANT ALL ON FUNCTIONS TO anon;
ALTER DEFAULT PRIVILEGES FOR ROLE postgres IN SCHEMA public GRANT ALL ON FUNCTIONS TO authenticated;
ALTER DEFAULT PRIVILEGES FOR ROLE postgres IN SCHEMA public GRANT ALL ON FUNCTIONS TO service_role;


--
-- Name: DEFAULT PRIVILEGES FOR FUNCTIONS; Type: DEFAULT ACL; Schema: public; Owner: supabase_admin
--

ALTER DEFAULT PRIVILEGES FOR ROLE supabase_admin IN SCHEMA public GRANT ALL ON FUNCTIONS TO postgres;
ALTER DEFAULT PRIVILEGES FOR ROLE supabase_admin IN SCHEMA public GRANT ALL ON FUNCTIONS TO anon;
ALTER DEFAULT PRIVILEGES FOR ROLE supabase_admin IN SCHEMA public GRANT ALL ON FUNCTIONS TO authenticated;
ALTER DEFAULT PRIVILEGES FOR ROLE supabase_admin IN SCHEMA public GRANT ALL ON FUNCTIONS TO service_role;


--
-- Name: DEFAULT PRIVILEGES FOR TABLES; Type: DEFAULT ACL; Schema: public; Owner: postgres
--

ALTER DEFAULT PRIVILEGES FOR ROLE postgres IN SCHEMA public GRANT ALL ON TABLES TO postgres;
ALTER DEFAULT PRIVILEGES FOR ROLE postgres IN SCHEMA public GRANT ALL ON TABLES TO anon;
ALTER DEFAULT PRIVILEGES FOR ROLE postgres IN SCHEMA public GRANT ALL ON TABLES TO authenticated;
ALTER DEFAULT PRIVILEGES FOR ROLE postgres IN SCHEMA public GRANT ALL ON TABLES TO service_role;


--
-- Name: DEFAULT PRIVILEGES FOR TABLES; Type: DEFAULT ACL; Schema: public; Owner: supabase_admin
--

ALTER DEFAULT PRIVILEGES FOR ROLE supabase_admin IN SCHEMA public GRANT ALL ON TABLES TO postgres;
ALTER DEFAULT PRIVILEGES FOR ROLE supabase_admin IN SCHEMA public GRANT ALL ON TABLES TO anon;
ALTER DEFAULT PRIVILEGES FOR ROLE supabase_admin IN SCHEMA public GRANT ALL ON TABLES TO authenticated;
ALTER DEFAULT PRIVILEGES FOR ROLE supabase_admin IN SCHEMA public GRANT ALL ON TABLES TO service_role;


--
-- PostgreSQL database dump complete
--

