--
-- PostgreSQL database dump
--

-- Dumped from database version 15.1 (Ubuntu 15.1-1.pgdg20.04+1)
-- Dumped by pg_dump version 16.1

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- Name: link; Type: TABLE; Schema: public; Owner: supabase_admin
--

CREATE TABLE public.link (
    id bigint NOT NULL,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    id_parent bigint NOT NULL,
    id_child bigint NOT NULL
);


ALTER TABLE public.link OWNER TO supabase_admin;

--
-- Name: link_id_seq; Type: SEQUENCE; Schema: public; Owner: supabase_admin
--

ALTER TABLE public.link ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.link_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: link link_pkey; Type: CONSTRAINT; Schema: public; Owner: supabase_admin
--

ALTER TABLE ONLY public.link
    ADD CONSTRAINT link_pkey PRIMARY KEY (id);


--
-- Name: link uniq_link_by_parent_n_child; Type: CONSTRAINT; Schema: public; Owner: supabase_admin
--

ALTER TABLE ONLY public.link
    ADD CONSTRAINT uniq_link_by_parent_n_child UNIQUE (id_parent, id_child);


--
-- Name: link link_id_child_fkey; Type: FK CONSTRAINT; Schema: public; Owner: supabase_admin
--

ALTER TABLE ONLY public.link
    ADD CONSTRAINT link_id_child_fkey FOREIGN KEY (id_child) REFERENCES public.thing(id);


--
-- Name: link link_id_parent_fkey; Type: FK CONSTRAINT; Schema: public; Owner: supabase_admin
--

ALTER TABLE ONLY public.link
    ADD CONSTRAINT link_id_parent_fkey FOREIGN KEY (id_parent) REFERENCES public.thing(id);


--
-- Name: link; Type: ROW SECURITY; Schema: public; Owner: supabase_admin
--

ALTER TABLE public.link ENABLE ROW LEVEL SECURITY;

--
-- Name: TABLE link; Type: ACL; Schema: public; Owner: supabase_admin
--

GRANT ALL ON TABLE public.link TO postgres;
GRANT ALL ON TABLE public.link TO anon;
GRANT ALL ON TABLE public.link TO authenticated;
GRANT ALL ON TABLE public.link TO service_role;


--
-- Name: SEQUENCE link_id_seq; Type: ACL; Schema: public; Owner: supabase_admin
--

GRANT ALL ON SEQUENCE public.link_id_seq TO postgres;
GRANT ALL ON SEQUENCE public.link_id_seq TO anon;
GRANT ALL ON SEQUENCE public.link_id_seq TO authenticated;
GRANT ALL ON SEQUENCE public.link_id_seq TO service_role;


--
-- PostgreSQL database dump complete
--

