-- public.link definition

-- Drop table

-- DROP TABLE public.link;

CREATE TABLE public.link (
	id int8 NOT NULL GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START 1 CACHE 1 NO CYCLE),
	created_at timestamptz NOT NULL DEFAULT now(),
	id_parent int8 NOT NULL,
	id_child int8 NOT NULL,
	CONSTRAINT link_pkey PRIMARY KEY (id),
	CONSTRAINT uniq_link_by_parent_n_child UNIQUE (id_parent, id_child),
	CONSTRAINT link_id_child_fkey FOREIGN KEY (id_child) REFERENCES public.thing(id),
	CONSTRAINT link_id_parent_fkey FOREIGN KEY (id_parent) REFERENCES public.thing(id)
);

-- Permissions

ALTER TABLE public.link OWNER TO supabase_admin;
GRANT ALL ON TABLE public.link TO supabase_admin;
GRANT ALL ON TABLE public.link TO anon;
GRANT ALL ON TABLE public.link TO authenticated;
GRANT ALL ON TABLE public.link TO service_role;
GRANT ALL ON TABLE public.link TO postgres;