-- public.availability definition

-- Drop table

-- DROP TABLE public.availability;

CREATE TABLE public.availability (
	id int4 NOT NULL GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START 1 CACHE 1 NO CYCLE),
	created_at timestamptz NOT NULL DEFAULT now(),
	id_thing int8 NOT NULL,
	"start" timestamptz NOT NULL,
	stop timestamptz NOT NULL,
	CONSTRAINT availability_pkey PRIMARY KEY (id),
	CONSTRAINT uniq_availability_by_thing_n_start_n_stop UNIQUE (id_thing, start, stop),
	CONSTRAINT availability_id_thing_fkey FOREIGN KEY (id_thing) REFERENCES public.thing(id)
);

-- Permissions

ALTER TABLE public.availability OWNER TO supabase_admin;
GRANT ALL ON TABLE public.availability TO supabase_admin;
GRANT ALL ON TABLE public.availability TO anon;
GRANT ALL ON TABLE public.availability TO authenticated;
GRANT ALL ON TABLE public.availability TO service_role;
GRANT ALL ON TABLE public.availability TO postgres;